# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NameNode.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eNameNode.proto\x12\x10NameNode.Service\"\x1d\n\x0fUploadDBRequest\x12\n\n\x02\x64\x62\x18\x01 \x01(\x0c\"3\n\x10UploadDBResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x10HeartBeatRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"4\n\x11HeartBeatResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x11\x44ownloadDBRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"5\n\x12\x44ownloadDBResponse\x12\x13\n\x0b\x63\x61nDownload\x18\x01 \x01(\x08\x12\n\n\x02\x64\x62\x18\x02 \x01(\x0c\x32\x93\x02\n\tDBService\x12S\n\x08UploadDB\x12!.NameNode.Service.UploadDBRequest\x1a\".NameNode.Service.UploadDBResponse\"\x00\x12Y\n\nDownloadDB\x12#.NameNode.Service.DownloadDBRequest\x1a$.NameNode.Service.DownloadDBResponse\"\x00\x12V\n\tHeartBeat\x12\".NameNode.Service.HeartBeatRequest\x1a#.NameNode.Service.HeartBeatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NameNode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPLOADDBREQUEST']._serialized_start=36
  _globals['_UPLOADDBREQUEST']._serialized_end=65
  _globals['_UPLOADDBRESPONSE']._serialized_start=67
  _globals['_UPLOADDBRESPONSE']._serialized_end=118
  _globals['_HEARTBEATREQUEST']._serialized_start=120
  _globals['_HEARTBEATREQUEST']._serialized_end=178
  _globals['_HEARTBEATRESPONSE']._serialized_start=180
  _globals['_HEARTBEATRESPONSE']._serialized_end=232
  _globals['_DOWNLOADDBREQUEST']._serialized_start=234
  _globals['_DOWNLOADDBREQUEST']._serialized_end=267
  _globals['_DOWNLOADDBRESPONSE']._serialized_start=269
  _globals['_DOWNLOADDBRESPONSE']._serialized_end=322
  _globals['_DBSERVICE']._serialized_start=325
  _globals['_DBSERVICE']._serialized_end=600
# @@protoc_insertion_point(module_scope)
